language: python

python:
  - "2.7"

reset_minion: true

env:
  - DJANGO=1.7
  - DJANGO=1.6
  - DJANGO=1.5

install:
  - pip install Django\<$DJANGO djangocms-helper pysqlite
  - python setup.py install

script:
  - make runtest
