language: python

python: 3.5

sudo: false

env:
  matrix:
    # Matrix-size reduction strategies:
    #   PY strategy: do not test 3.3 at all.
    #   FE strategy: only test on Django/CMS3.3 combinations, but place tests on
    #                different Python ENVs if possible.
    - TOXENV=flake8

    - TOXENV=py35-dj110-cms35
    - TOXENV=py35-dj110-cms34
    - TOXENV=py34-dj110-cms35
    - TOXENV=py34-dj110-cms34
    - TOXENV=py27-dj110-cms35
    - TOXENV=py27-dj110-cms34

    - TOXENV=py35-dj19-cms34
    - TOXENV=py35-dj19-cms33
    - TOXENV=py35-dj19-cms32
    - TOXENV=py34-dj19-cms34
    - TOXENV=py34-dj19-cms33
    - TOXENV=py34-dj19-cms32
    - TOXENV=py27-dj19-cms34
    - TOXENV=py27-dj19-cms33
    - TOXENV=py27-dj19-cms32
    - TOXENV=py35-dj19-cms33-fe FE=1

    - TOXENV=py35-dj18-cms34
    - TOXENV=py35-dj18-cms33
    - TOXENV=py35-dj18-cms32
    - TOXENV=py34-dj18-cms34
    - TOXENV=py34-dj18-cms33
    - TOXENV=py34-dj18-cms32
    - TOXENV=py27-dj18-cms34
    - TOXENV=py27-dj18-cms33
    - TOXENV=py27-dj18-cms32
    - TOXENV=py27-dj18-cms33-fe FE=1

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

before_script:
  - if [ "$FE" == 1 ]; then nvm install 6 && nvm use 6; fi
  - if [ "$FE" == 1 ]; then npm config set spin false; fi
  - if [ "$FE" == 1 ]; then npm install -g gulp@3.9.0; fi
  - if [ "$FE" == 1 ]; then npm install -g codeclimate-test-reporter; fi
  - if [ "$FE" == 1 ]; then npm install; fi

script:
  - tox -e $TOXENV

after_script:
  - codeclimate < tests/coverage/**/lcov.info

after_success: coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
