language: python

sudo: false

env:
  global:
    # encrypted Sauce Labs sub-account user name
    - secure: OIkBwlWwClimhBeKs4kT4Elkp9fx+pjEBKJlZY+TpIXsjqskKgSbsnDkBcQuW9cJoj4qCddRAKOzN/XD3tT+ZAbo/257lSMcDCdslqxehd/JJVCfglANGioMxHUmZ9F5EDrc+ZtnQ40O5tcFNHRgJXR92el931V379zs/9om8LY=
    # encrypted Sauce Labs sub-account token
    - secure: MWxL/6t1qI3TSIcBDDMtctIlvXjJtOCxMk0Xj4I7vzE5jvhBMhHT+1YBR8Wd8AykzbTmK5XAe4jhhBmlHannm5zRfmua9D+kpvGQH819V46setzluConoXTgPMWE7O9gtVeOiNBuLGD72ELO/X8ZbiYcO/JFsXbad5tNQZ3XTJo=
    # encrypted Code Climate token
    - secure: oJG/hKhutnzSFCSF8xUuMWmTxeuRp2eU9HBi/7JWVxd3AwDkKu3jtldQ0Vg/2iSofRzzG0wZpUKdgGa4ObOpOou5wWtq68OAVbJkHAtOB7U3HR4deVuQRZdR8GXWWS9G+H1B8PbFCVPzQrsnxHs/k0oBLUgAW8XfFfkhzzYGFKk=
  matrix:
    - TOXENV=flake8
    - TOXENV=py27-dj18-cms31
    - TOXENV=py27-dj17-cms31
    - TOXENV=py27-dj17-cms30
    - TOXENV=py27-dj16-cms31
    - TOXENV=py27-dj16-cms30
    - TOXENV=py26-dj16-cms31
    - TOXENV=py26-dj16-cms30

matrix:
  allow_failures:
    # allow failures with TOXENV=py27-dj18-cms31
    - env: TOXENV=py27-dj18-cms31

cache:
  directories:
    - $HOME/.wheelhouse

before_install:
  - npm install -g npm

install:
  - pip install tox
  - pip install coveralls

before_script:
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter
  - npm install

script:
  - tox -e $TOXENV

after_script:
  - codeclimate < tests/coverage/**/lcov.info

after_success: coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
